build_linux:
  stage: build
  script:
  - mkdir -p $CI_PROJECT_DIR/dist/linux
  - docker build -f Dockerfile-linux --build-arg cores=10 -t reptiloidscoindx/devbuilds:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-linux .
  - if [ ! -z "$(docker ps -qa -f name=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-linux)" ]; then docker rm $CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-linux; fi
  - docker create --name=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-linux reptiloidscoindx/devbuilds:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-linux
  - docker cp $CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-linux:/opt/reptiloidscoindx/dist/bin $CI_PROJECT_DIR/dist/linux
  - if [ ! -z "$(docker ps -qa -f name=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-linux)" ]; then docker rm $CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-linux; fi
  artifacts:
    name: "reptiloidscoin-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-linux"
    expire_in: 3 weeks
    paths:
    - dist/linux/bin

test_linux:
  stage: test
  script:
  - "[ -f \"$CI_PROJECT_DIR/dist/linux/bin/reptiloidscoin-cli\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/linux/bin/reptiloidscoind\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/linux/bin/reptiloidscoin-qt\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/linux/bin/reptiloidscoin-tx\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/linux/bin/reptiloidscoin-wallet\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/linux/bin/test_reptiloidscoin\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/linux/bin/test_reptiloidscoin-qt\" ];"

build_win:
  stage: build
  script:
  - mkdir -p $CI_PROJECT_DIR/dist/win
  - docker build -f Dockerfile-win --build-arg cores=10 -t reptiloidscoindx/devbuilds:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-win .
  - if [ ! -z "$(docker ps -qa -f name=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-win)" ]; then docker rm $CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-win; fi
  - docker create --name=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-win reptiloidscoindx/devbuilds:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-win
  - docker cp $CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-win:/opt/reptiloidscoindx/dist/bin $CI_PROJECT_DIR/dist/win
  - if [ ! -z "$(docker ps -qa -f name=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-win)" ]; then docker rm $CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-win; fi
  artifacts:
    name: "reptiloidscoin-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-win"
    expire_in: 3 weeks
    paths:
    - dist/win/bin

test_win:
  stage: test
  script:
  - "[ -f \"$CI_PROJECT_DIR/dist/win/bin/reptiloidscoin-cli.exe\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/win/bin/reptiloidscoind.exe\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/win/bin/reptiloidscoin-qt.exe\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/win/bin/reptiloidscoin-tx.exe\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/win/bin/reptiloidscoin-wallet.exe\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/win/bin/test_reptiloidscoin.exe\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/win/bin/reptiloidscoin-win64-setup.exe\" ];"

build_mac:
  stage: build
  script:
  - mkdir -p $CI_PROJECT_DIR/dist/mac
  - docker build -f Dockerfile-mac --build-arg cores=10 -t reptiloidscoindx/devbuilds:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-mac .
  - if [ ! -z "$(docker ps -qa -f name=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-mac)" ]; then docker rm $CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-mac; fi
  - docker create --name=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-mac reptiloidscoindx/devbuilds:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-mac
  - docker cp $CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-mac:/opt/reptiloidscoindx/dist/bin $CI_PROJECT_DIR/dist/mac
  - if [ ! -z "$(docker ps -qa -f name=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-mac)" ]; then docker rm $CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-mac; fi
  artifacts:
    name: "reptiloidscoin-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-mac"
    expire_in: 3 weeks
    paths:
    - dist/mac/bin

test_mac:
  stage: test
  script:
  - "[ -f \"$CI_PROJECT_DIR/dist/mac/bin/reptiloidscoin-cli\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/mac/bin/reptiloidscoind\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/mac/bin/reptiloidscoin-qt\" ];"
  - "[ -d \"$CI_PROJECT_DIR/dist/mac/bin/reptiloidscoin-qt.dSYM\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/mac/bin/reptiloidscoin-tx\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/mac/bin/reptiloidscoin-wallet\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/mac/bin/test_reptiloidscoin\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/mac/bin/test_reptiloidscoin-qt\" ];"
