build_linux:
  stage: build
  script:
  - mkdir -p $CI_PROJECT_DIR/dist/linux
  - docker build -f Dockerfile-linux --build-arg cores=10 -t reptiloidsdx/devbuilds:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-linux .
  - if [ ! -z "$(docker ps -qa -f name=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-linux)" ]; then docker rm $CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-linux; fi
  - docker create --name=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-linux reptiloidsdx/devbuilds:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-linux
  - docker cp $CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-linux:/opt/reptiloidsdx/dist/bin $CI_PROJECT_DIR/dist/linux
  - if [ ! -z "$(docker ps -qa -f name=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-linux)" ]; then docker rm $CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-linux; fi
  artifacts:
    name: "reptiloids-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-linux"
    expire_in: 3 weeks
    paths:
    - dist/linux/bin

test_linux:
  stage: test
  script:
  - "[ -f \"$CI_PROJECT_DIR/dist/linux/bin/reptiloids-cli\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/linux/bin/reptiloidsd\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/linux/bin/reptiloids-qt\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/linux/bin/reptiloids-tx\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/linux/bin/reptiloids-wallet\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/linux/bin/test_reptiloids\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/linux/bin/test_reptiloids-qt\" ];"

build_win:
  stage: build
  script:
  - mkdir -p $CI_PROJECT_DIR/dist/win
  - docker build -f Dockerfile-win --build-arg cores=10 -t reptiloidsdx/devbuilds:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-win .
  - if [ ! -z "$(docker ps -qa -f name=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-win)" ]; then docker rm $CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-win; fi
  - docker create --name=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-win reptiloidsdx/devbuilds:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-win
  - docker cp $CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-win:/opt/reptiloidsdx/dist/bin $CI_PROJECT_DIR/dist/win
  - if [ ! -z "$(docker ps -qa -f name=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-win)" ]; then docker rm $CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-win; fi
  artifacts:
    name: "reptiloids-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-win"
    expire_in: 3 weeks
    paths:
    - dist/win/bin

test_win:
  stage: test
  script:
  - "[ -f \"$CI_PROJECT_DIR/dist/win/bin/reptiloids-cli.exe\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/win/bin/reptiloidsd.exe\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/win/bin/reptiloids-qt.exe\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/win/bin/reptiloids-tx.exe\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/win/bin/reptiloids-wallet.exe\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/win/bin/test_reptiloids.exe\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/win/bin/reptiloids-win64-setup.exe\" ];"

build_mac:
  stage: build
  script:
  - mkdir -p $CI_PROJECT_DIR/dist/mac
  - docker build -f Dockerfile-mac --build-arg cores=10 -t reptiloidsdx/devbuilds:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-mac .
  - if [ ! -z "$(docker ps -qa -f name=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-mac)" ]; then docker rm $CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-mac; fi
  - docker create --name=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-mac reptiloidsdx/devbuilds:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-mac
  - docker cp $CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-mac:/opt/reptiloidsdx/dist/bin $CI_PROJECT_DIR/dist/mac
  - if [ ! -z "$(docker ps -qa -f name=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-mac)" ]; then docker rm $CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-mac; fi
  artifacts:
    name: "reptiloids-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-mac"
    expire_in: 3 weeks
    paths:
    - dist/mac/bin

test_mac:
  stage: test
  script:
  - "[ -f \"$CI_PROJECT_DIR/dist/mac/bin/reptiloids-cli\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/mac/bin/reptiloidsd\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/mac/bin/reptiloids-qt\" ];"
  - "[ -d \"$CI_PROJECT_DIR/dist/mac/bin/reptiloids-qt.dSYM\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/mac/bin/reptiloids-tx\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/mac/bin/reptiloids-wallet\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/mac/bin/test_reptiloids\" ];"
  - "[ -f \"$CI_PROJECT_DIR/dist/mac/bin/test_reptiloids-qt\" ];"
